package com.jobsearchassistant.fit;

enum FitReasonCode {
    NO_CONFIRMED_REQUIREMENTS,
    NO_LINKED_EVIDENCE,
    SUPPORTING_EVIDENCE,
    PARTIAL_SUPPORTING_EVIDENCE,
    ONLY_NOT_DEMONSTRATED_EVIDENCE,
    CONTRADICTING_EVIDENCE,
    CONFLICTING_SUPPORT_AND_CONTRADICTION
}
